### ISSUE TITLE
Model can't be loaded

### ISSUE THREAD

**Issue by yzfly** [andriydruk/LMPlayground#2]
hi， thank you for sharing the code.  After follow development guide, I can compile the app correctly and install the app on my andorid phone. but it can't load the model after the model is downloaded, seems the llama.cpp don't load the model well, is there any idea? or is there a more detailed develop guide?

**Comment by andriydruk** [comment]
Hi, 
Please share logs from LogCat. If crash occurred please share stacktrace. 
Do you experienced issue on version from Google Play?

**Comment by cparish312** [comment]
@yzfly I had the same issue. Try deleting all of the models in your Downloads folder. It could be because the model name has "-1" appended since the built app doesn't have access to the previously downloaded model.

**Comment by yzfly** [comment]
> @yzfly I had the same issue. Try deleting all of the models in your Downloads folder. It could be because the model name has "-1" appended since the built app doesn't have access to the previously downloaded model.

thank you so much!
